#!/bin/bash

clear

# Colors
RED='\033[0;31m'
GRN='\033[0;32m'
CYN='\033[0;36m'
YEL='\033[1;33m'
NC='\033[0m' # No Color

# ASCII Art Banner
echo -e "${YEL}"
cat << "EOF"
__________    ________ 
          _____                            _____          
         /\    \                          /\    \         
        /::\    \                        /::\    \        
       /::::\    \                      /::::\    \       
      /::::::\    \                    /::::::\    \      
     /:::/\:::\    \                  /:::/\:::\    \     
    /:::/__\:::\    \                /:::/  \:::\    \    
   /::::\   \:::\    \              /:::/    \:::\    \   
  /::::::\   \:::\    \            /:::/    / \:::\    \  
 /:::/\:::\   \:::\____\          /:::/    /   \:::\ ___\ 
/:::/  \:::\   \:::|    |        /:::/____/  ___\:::|    |
\::/   |::::\  /:::|____|        \:::\    \ /\  /:::|____|
 \/____|:::::\/:::/    /          \:::\    /::\ \::/    / 
       |:::::::::/    /            \:::\   \:::\ \/____/  
       |::|\::::/    /              \:::\   \:::\____\    
       |::| \::/____/                \:::\  /:::/    /    
       |::|  ~|                       \:::\/:::/    /     
       |::|   |                        \::::::/    /      
       \::|   |                         \::::/    /       
        \:|   |                          \::/____/        
         \|___|                                        
EOF
echo -e "${NC}"

# Subscribe animation
echo -ne "${GRN}🔥 Please Subscribe \n"
for i in {1..3}; do
  echo -ne "${CYN}Subscribing To RasINGamerZ"
  for dot in {1..3}; do
    echo -n "."
    sleep 0.3
  done
  echo -ne "\r                     \r"
done
echo -e "${GRN} Thanks for Subscribing! If Not Do It Rn${NC}\n"
sleep 1

# Install PufferPanel
echo -e "${YEL}🚀 Installing PufferPanel...${NC}"

sudo apt update  -y

sudo apt install -y sudo

sudo apt install -y systemctl

curl -s https://packagecloud.io/install/repositories/pufferpanel/pufferpanel/script.deb.sh?any=true | sudo bash

sudo apt update -y

sudo apt-get install -y pufferpanel

sudo pufferpanel user add

sudo systemctl enable --now pufferpanel

echo -e "${GRN}✅ PufferPanel installation complete!${NC}"
